// Copyright (c) Microsoft Corporation.  All rights reserved.

namespace Microsoft.Azure.Cosmos.NativeDriverPoc
{
    using System;
    using System.Runtime.InteropServices;

    /// <summary>
    /// Raw P/Invoke surface for <c>azurecosmosdriver.dll</c> — the cdylib
    /// produced by the <c>azure_data_cosmos_driver_native</c> crate in
    /// PR https://github.com/Azure/azure-sdk-for-rust/pull/4515.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Source of truth for every signature in this file is the cbindgen-
    /// generated <c>include/azurecosmosdriver.h</c> at
    /// commit <c>users/kundadebdatta/4372_cosmos_driver_native_crate_async_impl</c>
    /// (cached in <c>Q:\src\.poc-artifacts\pr4515\azurecosmosdriver.h</c>).
    /// </para>
    /// <para>
    /// Scope: this V2 binding covers the Phase 0–6 surface needed for
    /// single-item CRUD against the emulator. The remaining ~30 functions
    /// in the header (driver_options builder, operation_options builder,
    /// feed_range, query_items, batch, async submit variants, response
    /// take_driver/take_container, backtrace options) are intentionally
    /// unbound — they are additive and can be layered in without rewriting
    /// any existing binding.
    /// </para>
    /// <para>
    /// Known gap in PR #4515 (worth a comment on the PR):
    /// the six item-CRUD factory functions
    /// (<c>cosmos_operation_{create,read,upsert,replace,delete,patch}_item</c>)
    /// are generated by the <c>item_factory!</c> macro in
    /// <c>operation.rs</c> (line 441). They are <c>#[no_mangle]</c> so they
    /// are exported from the cdylib, but cbindgen does NOT emit them into
    /// <c>azurecosmosdriver.h</c> — a known cbindgen limitation with
    /// macro-expanded exports. Our P/Invoke resolves them by symbol name
    /// at runtime, so the .NET side is unaffected; the README quick-start
    /// in the PR uses them too.
    /// </para>
    /// </remarks>
    internal static class NativeMethods
    {
        public const string LibraryName = "azurecosmosdriver";

        // -----------------------------------------------------------------
        // Enums — all values verified against azurecosmosdriver.h
        // -----------------------------------------------------------------

        /// <summary>
        /// Header lines 107–268. 34-variant taxonomy spanning argument
        /// validation (1–2), wire-mapped HTTP (2xxx), client-side
        /// driver (3xxx), wrapper-fatal (4xxx), and warnings (5xxx).
        /// </summary>
        public enum CosmosErrorCode : int
        {
            Success = 0,

            // 1..=999 — FFI / argument validation
            InvalidArgument = 1,
            InvalidUtf8 = 2,

            // 2xxx — wire-mapped HTTP statuses
            BadRequest = 2400,
            Unauthorized = 2401,
            Forbidden = 2403,
            NotFound = 2404,
            Timeout = 2408,
            Conflict = 2409,
            Gone = 2410,
            PreconditionFailed = 2412,
            Throttled = 2429,
            ServiceUnavailable = 2503,
            ServiceError = 2999,

            // 3xxx — driver client-side / synthetic
            ClientError = 3001,
            TransportFailure = 3002,
            SerializationFailed = 3003,
            AuthenticationFailed = 3004,
            ClientOperationTimeout = 3005,

            // 4xxx — driver-wrapper-specific fatal
            DriverNotInitialized = 4002,
            InvalidAccountReference = 4003,
            InvalidPartitionKey = 4004,
            OperationConsumed = 4005,
            ResponseConsumed = 4006,
            FeedExhausted = 4007,
            PreconditionAlreadySet = 4008,
            UnsupportedOperationForMutator = 4009,
            InvalidHeader = 4010,
            QueueShutdown = 4011,
            OperationCancelled = 4012,
            QueueFull = 4013,
            InvalidOptionValue = 4014,
            RuntimeBuildFailed = 4015,

            // 5xxx — non-fatal warnings
            OptionsIgnoredOnCacheHit = 5001,
        }

        /// <summary>Header lines 19–45.</summary>
        public enum CosmosCqState : int
        {
            Running = 0,
            Shutdown = 1,
            Drained = 2,
        }

        /// <summary>Header lines 54–85.</summary>
        public enum CosmosCompletionOutcome : int
        {
            Ok = 0,
            Error = 1,
            Cancelled = 2,
            Unknown = 255,
        }

        /// <summary>Header lines 273–301.</summary>
        public enum CosmosOperationHandleState : int
        {
            InFlight = 0,
            Completed = 1,
            Failed = 2,
            Cancelled = 3,
        }

        // -----------------------------------------------------------------
        // Structs — pass-by-value across the ABI
        // -----------------------------------------------------------------

        /// <summary>Header lines 447–451. Layout published per spec §3.1.2.</summary>
        [StructLayout(LayoutKind.Sequential)]
        public struct CosmosCqOptions
        {
            public uint CapacityHint;
            public uint MaxCapacity;
            [MarshalAs(UnmanagedType.U1)]
            public bool IncludeErrorDetails;

            public static CosmosCqOptions Default => new CosmosCqOptions
            {
                CapacityHint = 1024,
                MaxCapacity = 0,
                IncludeErrorDetails = true,
            };
        }

        // -----------------------------------------------------------------
        // Misc — Phase 0
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_version();

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_string_free(IntPtr s);

        // -----------------------------------------------------------------
        // Opaque bytes handle — Phase 0 (header lines 405–694)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_bytes_data(IntPtr b);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern UIntPtr cosmos_bytes_len(IntPtr b);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_bytes_free(IntPtr b);

        // -----------------------------------------------------------------
        // Runtime builder — Phase 2 (header lines 1649–1747)
        // NOTE: Only the 5 setters listed below exist. There is no
        // worker_threads / thread_name_prefix / allow_emulator setter —
        // emulator cert handling lives at the driver_options layer (or
        // env-var bundles); Tokio worker count is non-configurable.
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_runtime_builder_new();

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_runtime_builder_free(IntPtr builder);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_runtime_builder_with_workload_id(
            IntPtr builder, byte workloadId);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_runtime_builder_with_correlation_id(
            IntPtr builder, [MarshalAs(UnmanagedType.LPUTF8Str)] string correlationId);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_runtime_builder_with_user_agent_suffix(
            IntPtr builder, [MarshalAs(UnmanagedType.LPUTF8Str)] string suffix);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_runtime_builder_with_wrapping_sdk_identifier(
            IntPtr builder, [MarshalAs(UnmanagedType.LPUTF8Str)] string identifier);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_runtime_builder_with_cpu_refresh_interval_ms(
            IntPtr builder, ulong intervalMs);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_runtime_builder_build(
            IntPtr builder,
            out IntPtr outRuntime,
            out IntPtr outError);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_runtime_free(IntPtr runtime);

        // -----------------------------------------------------------------
        // Completion queue — Phase 1 (header lines 696–767)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_cq_create(IntPtr runtime, in CosmosCqOptions options);

        /// <summary>Pointer-overload — pass <see cref="IntPtr.Zero"/> for defaults.</summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "cosmos_cq_create")]
        public static extern IntPtr cosmos_cq_create_default(IntPtr runtime, IntPtr nullOptions);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_cq_free(IntPtr cq);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_cq_shutdown(IntPtr cq);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosCqState cosmos_cq_state(IntPtr cq);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_cq_wait(IntPtr cq, uint timeoutMs);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_cq_try_wait(IntPtr cq);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint cosmos_cq_wait_batch(
            IntPtr cq,
            [Out] IntPtr[] outCompletions,
            uint maxCount,
            uint timeoutMs);

        // -----------------------------------------------------------------
        // Completion record — Phase 1 (header lines 770–835)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosCompletionOutcome cosmos_completion_outcome(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_user_data(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_op_handle(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_completion_status(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool cosmos_completion_was_cancel_requested(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_take_response(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_response(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_take_error(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_error(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_completion_free(IntPtr c);

        // -----------------------------------------------------------------
        // Operation handle — Phase 1 (header lines 837–858)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_operation_handle_cancel(IntPtr op);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosOperationHandleState cosmos_operation_handle_state(IntPtr op);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_operation_handle_free(IntPtr op);

        // -----------------------------------------------------------------
        // Account / database / container refs — Phase 3
        // (header lines 617–947, 1640)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_account_ref_with_master_key(
            [MarshalAs(UnmanagedType.LPUTF8Str)] string endpoint,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string key,
            out IntPtr outAccount,
            out IntPtr outError);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_account_ref_clone(
            IntPtr account, out IntPtr outClone);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_account_ref_free(IntPtr account);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_database_ref_create(
            IntPtr account,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string databaseId,
            out IntPtr outDatabase);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_database_ref_free(IntPtr database);

        /// <summary>
        /// Header lines 894–899. Containers are NOT constructed by name —
        /// they are resolved by the driver (potential network round-trip
        /// to read the container's partition-key definition). Sync variant.
        /// </summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_driver_resolve_container_blocking(
            IntPtr runtime,
            IntPtr driver,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string databaseId,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string containerId,
            out IntPtr outContainer,
            out IntPtr outError);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_container_ref_free(IntPtr container);

        // -----------------------------------------------------------------
        // Driver — Phase 3 (header lines 942–997)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_driver_get_or_create_blocking(
            IntPtr runtime,
            IntPtr account,
            IntPtr options,
            out IntPtr outDriver,
            out IntPtr outError);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_driver_free(IntPtr driver);

        // -----------------------------------------------------------------
        // Partition key — Phase 4 (header lines 1453–1560)
        // The string-only convenience does NOT exist; must use builder.
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_partition_key_builder_new();

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_partition_key_builder_free(IntPtr builder);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_add_string(
            IntPtr builder, [MarshalAs(UnmanagedType.LPUTF8Str)] string value);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_add_number(
            IntPtr builder, double value);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_add_bool(
            IntPtr builder, [MarshalAs(UnmanagedType.U1)] bool value);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_add_null(IntPtr builder);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_add_undefined(IntPtr builder);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_build(
            IntPtr builder, out IntPtr outPk);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_partition_key_empty();

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_partition_key_free(IntPtr pk);

        // -----------------------------------------------------------------
        // Item-CRUD operation factories — Phase 6
        //
        // NOT DECLARED IN THE HEADER (cbindgen + item_factory! macro gap).
        // Declarations confirmed at operation.rs:443-466. P/Invoke resolves
        // by symbol name at runtime; the DLL exports them because the
        // macro emits #[no_mangle].
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_operation_read_item(
            IntPtr container,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string itemId,
            IntPtr partitionKey,
            out IntPtr outOp);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_operation_create_item(
            IntPtr container,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string itemId,
            IntPtr partitionKey,
            out IntPtr outOp);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_operation_upsert_item(
            IntPtr container,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string itemId,
            IntPtr partitionKey,
            out IntPtr outOp);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_operation_replace_item(
            IntPtr container,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string itemId,
            IntPtr partitionKey,
            out IntPtr outOp);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_operation_delete_item(
            IntPtr container,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string itemId,
            IntPtr partitionKey,
            out IntPtr outOp);

        // -----------------------------------------------------------------
        // Operation body mutator — Phase 6 (header lines 1257–1259)
        // Real signature uses (op, *uint8, uintptr) — NOT a bytes_view struct.
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_operation_with_body(
            IntPtr op, byte[] body, UIntPtr bodyLen);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_operation_free(IntPtr op);

        // -----------------------------------------------------------------
        // Submission — Phase 6 (header lines 1790–1795)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_driver_submit(
            IntPtr driver,
            IntPtr op,
            IntPtr options,
            IntPtr cq,
            IntPtr userData,
            out CosmosErrorCode outPreError);

        // -----------------------------------------------------------------
        // Response — Phase 6 (header lines 1562–1613)
        // cosmos_response_body returns int32_t + out-params (NOT a struct).
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern ushort cosmos_response_status_code(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern double cosmos_response_request_charge(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_activity_id(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_session_token(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_etag(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_continuation_token(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_response_body(
            IntPtr response, out IntPtr outData, out UIntPtr outLen);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_response_free(IntPtr response);

        // -----------------------------------------------------------------
        // Rich error — Phase 1 (header lines 1082–1137)
        // NO cosmos_error_kind() — kind lives implicitly in CosmosErrorCode.
        // NO is_throttled/is_not_found/etc. — use cosmos_completion_status
        // and compare against the enum band (2429 = THROTTLED, etc.).
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern ushort cosmos_error_status_code(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int cosmos_error_sub_status(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool cosmos_error_is_from_wire(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_error_message(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_error_activity_id(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_error_session_token(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_error_etag(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern long cosmos_error_retry_after_ms(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_error_backtrace(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_error_free(IntPtr e);

        // -----------------------------------------------------------------
        // Common helper — borrowed C string → managed String
        // -----------------------------------------------------------------

        /// <summary>Marshal a borrowed UTF-8 C string; returns null for NULL.</summary>
        public static string? PtrToUtf8(IntPtr ptr) =>
            ptr == IntPtr.Zero ? null : Marshal.PtrToStringUTF8(ptr);
    }
}
