// Copyright (c) Microsoft Corporation.  All rights reserved.

namespace Microsoft.Azure.Cosmos.NativeDriverPoc
{
    using System;
    using System.Runtime.InteropServices;

    /// <summary>
    /// Raw P/Invoke surface for <c>azurecosmosdriver.dll</c> — the cdylib
    /// produced by the <c>azure_data_cosmos_driver_native</c> crate in
    /// PR https://github.com/Azure/azure-sdk-for-rust/pull/4515.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Source of truth for every signature in this file is the cbindgen-
    /// generated <c>include/azurecosmosdriver.h</c> at PR head
    /// <c>4be377483</c> on branch
    /// <c>users/kundadebdatta/4372_cosmos_driver_native_crate_async_impl</c>.
    /// </para>
    /// <para>
    /// Architecture (post-redesign, commits <c>d748def8d</c> + <c>4ecdf69ad</c>):
    /// the per-operation factories that used to be generated by the
    /// <c>item_factory!</c> macro are GONE; <c>operation.rs</c> and
    /// <c>operation_options.rs</c> were deleted. Their ~3,000 LOC of
    /// per-op surface is replaced by:
    /// <list type="bullet">
    ///   <item>One flat <see cref="CosmosOperationRequest"/> struct (17 fields)
    ///   that carries every input every kind could need (kind, refs, ids,
    ///   body, tokens, precondition, options pointer).</item>
    ///   <item>One flat <see cref="CosmosOperationOptions"/> struct mirroring
    ///   the driver-side options bag, with tri-state encoding for every
    ///   field (<c>0</c> = inherit, &lt; 0 = unset numeric, NULL = unset string).</item>
    ///   <item>Two submit entry points: <see cref="cosmos_submit_singleton_operation"/>
    ///   for point ops and <see cref="cosmos_submit_operation"/>
    ///   for feed / paginated ops.</item>
    /// </list>
    /// </para>
    /// <para>
    /// Lifetime contract on submit: every borrowed pointer inside the
    /// request struct (UTF-8 strings, body bytes, options sub-struct)
    /// must remain valid for the duration of the single FFI call; the
    /// wrapper deep-copies before returning. Use
    /// <c>CosmosOperationRequestBuilder</c> to get the pinning right
    /// without hand-rolling <see cref="GCHandle"/> / <see cref="Marshal"/>
    /// dances at every call site.
    /// </para>
    /// </remarks>
    internal static class NativeMethods
    {
        public const string LibraryName = "azurecosmosdriver";

        // -----------------------------------------------------------------
        // Enums — all values verified against azurecosmosdriver.h
        // -----------------------------------------------------------------

        /// <summary>
        /// Header lines 107–268. 34-variant taxonomy spanning argument
        /// validation (1–2), wire-mapped HTTP (2xxx), client-side
        /// driver (3xxx), wrapper-fatal (4xxx), and warnings (5xxx).
        /// </summary>
        public enum CosmosErrorCode : int
        {
            Success = 0,

            // 1..=999 — FFI / argument validation
            InvalidArgument = 1,
            InvalidUtf8 = 2,

            // 2xxx — wire-mapped HTTP statuses
            BadRequest = 2400,
            Unauthorized = 2401,
            Forbidden = 2403,
            NotFound = 2404,
            Timeout = 2408,
            Conflict = 2409,
            Gone = 2410,
            PreconditionFailed = 2412,
            Throttled = 2429,
            ServiceUnavailable = 2503,
            ServiceError = 2999,

            // 3xxx — driver client-side / synthetic
            ClientError = 3001,
            TransportFailure = 3002,
            SerializationFailed = 3003,
            AuthenticationFailed = 3004,
            ClientOperationTimeout = 3005,

            // 4xxx — driver-wrapper-specific fatal
            DriverNotInitialized = 4002,
            InvalidAccountReference = 4003,
            InvalidPartitionKey = 4004,
            OperationConsumed = 4005,
            ResponseConsumed = 4006,
            FeedExhausted = 4007,
            PreconditionAlreadySet = 4008,
            UnsupportedOperationForMutator = 4009,
            InvalidHeader = 4010,
            QueueShutdown = 4011,
            OperationCancelled = 4012,
            QueueFull = 4013,
            InvalidOptionValue = 4014,
            RuntimeBuildFailed = 4015,

            // 5xxx — non-fatal warnings
            OptionsIgnoredOnCacheHit = 5001,
        }

        /// <summary>Header lines 19–45.</summary>
        public enum CosmosCqState : int
        {
            Running = 0,
            Shutdown = 1,
            Drained = 2,
        }

        /// <summary>Header lines 54–85.</summary>
        public enum CosmosCompletionOutcome : int
        {
            Ok = 0,
            Error = 1,
            Cancelled = 2,
            Unknown = 255,
        }

        /// <summary>Header lines 273–301.</summary>
        public enum CosmosOperationHandleState : int
        {
            InFlight = 0,
            Completed = 1,
            Failed = 2,
            Cancelled = 3,
        }

        // -----------------------------------------------------------------
        // New enums added by the PR #4515 redesign (header lines 303-487).
        // The four below back the flat CosmosOperationRequest /
        // CosmosOperationOptions structs introduced in op_request.rs.
        // -----------------------------------------------------------------

        /// <summary>
        /// Header lines 375-487. Discriminator the host stamps into the
        /// request struct so the driver knows which factory to invoke.
        /// Append-only: new kinds get new trailing discriminants.
        /// </summary>
        public enum CosmosOperationKind : int
        {
            Invalid = 0,
            CreateDatabase = 1,
            ReadAllDatabases = 2,
            QueryDatabases = 3,
            QueryOffers = 4,
            ReadOffer = 5,
            ReplaceOffer = 6,
            ReadDatabase = 7,
            DeleteDatabase = 8,
            CreateContainer = 9,
            ReadAllContainers = 10,
            QueryContainers = 11,
            ReadContainer = 12,
            ReplaceContainer = 13,
            DeleteContainer = 14,
            ReadAllItems = 15,
            ReadAllItemsCrossPartition = 16,
            QueryItems = 17,
            Batch = 18,
            CreateItem = 19,
            ReadItem = 20,
            UpsertItem = 21,
            ReplaceItem = 22,
            DeleteItem = 23,
            PatchItem = 24,
        }

        /// <summary>Header lines 492-516. Optimistic-concurrency selector.</summary>
        public enum CosmosPreconditionKind : int
        {
            None = 0,
            IfMatch = 1,
            IfNoneMatch = 2,
        }

        /// <summary>Header lines 307-339. Tri-state read-consistency strategy.</summary>
        public enum CosmosReadConsistencyStrategy : int
        {
            Unset = 0,
            Default = 1,
            Eventual = 2,
            Session = 3,
            GlobalStrong = 4,
        }

        /// <summary>Header lines 344-368. Tri-state content-response-on-write toggle.</summary>
        public enum CosmosContentResponseOnWriteOpt : int
        {
            Unset = 0,
            Disabled = 1,
            Enabled = 2,
        }

        // -----------------------------------------------------------------
        // Tri-state-bool sentinels for the int8_t fields on the options /
        // request structs (header lines 720-724, 911-919, etc.). Mirrors
        // op_request.rs::{TRISTATE_UNSET, TRISTATE_FALSE, TRISTATE_TRUE}.
        // -----------------------------------------------------------------

        public const sbyte TristateUnset = 0;
        public const sbyte TristateFalse = 1;
        public const sbyte TristateTrue = 2;

        // -----------------------------------------------------------------
        // Structs — pass-by-value across the ABI
        // -----------------------------------------------------------------

        /// <summary>Header lines 447–451. Layout published per spec §3.1.2.</summary>
        [StructLayout(LayoutKind.Sequential)]
        public struct CosmosCqOptions
        {
            public uint CapacityHint;
            public uint MaxCapacity;
            [MarshalAs(UnmanagedType.U1)]
            public bool IncludeErrorDetails;

            public static CosmosCqOptions Default => new CosmosCqOptions
            {
                CapacityHint = 1024,
                MaxCapacity = 0,
                IncludeErrorDetails = true,
            };
        }

        /// <summary>
        /// Header lines 831-840. Borrowed view of a request body. The
        /// wrapper copies the bytes into a driver-owned Vec&lt;u8&gt;
        /// before submit returns, so the host need only keep the buffer
        /// pinned across the single FFI call.
        /// </summary>
        [StructLayout(LayoutKind.Sequential)]
        public struct CosmosBytesView
        {
            /// <summary>Pointer to the first byte, or NULL when <c>Len</c> is 0.</summary>
            public IntPtr Data;
            /// <summary>Number of bytes.</summary>
            public UIntPtr Len;

            public static CosmosBytesView Empty => new CosmosBytesView
            {
                Data = IntPtr.Zero,
                Len = UIntPtr.Zero,
            };
        }

        /// <summary>
        /// Header lines 685-694. Single custom request/operation header
        /// (name + value, both NUL-terminated UTF-8, borrowed across submit).
        /// </summary>
        [StructLayout(LayoutKind.Sequential)]
        public struct CosmosHeaderKv
        {
            public IntPtr Name;
            public IntPtr Value;
        }

        /// <summary>
        /// Header lines 708-783. Flat C ABI mirror of the driver's
        /// <c>OperationOptions</c>. Every field is tri-state encoded;
        /// pass NULL for <c>CosmosOperationRequest.Options</c> to use
        /// the driver/runtime defaults for every field.
        /// </summary>
        /// <remarks>
        /// Construct via <see cref="cosmos_operation_options_default"/>
        /// to obtain an all-unset value, then mutate the fields you care
        /// about. Direct zero-init is also safe (every numeric "unset"
        /// sentinel is 0 / &lt; 0 / Unset).
        /// </remarks>
        [StructLayout(LayoutKind.Sequential)]
        public struct CosmosOperationOptions
        {
            public CosmosReadConsistencyStrategy ReadConsistencyStrategy;
            public CosmosContentResponseOnWriteOpt ContentResponseOnWrite;
            public sbyte SessionCapturingDisabled;
            public int MaxFailoverRetryCount;
            public int MaxSessionRetryCount;
            public long EndToEndTimeoutMs;
            public long EndpointUnavailabilityTtlMs;
            public IntPtr ThroughputControlGroup;
            public IntPtr ExcludedRegions;
            public UIntPtr ExcludedRegionsLen;
            public IntPtr CustomHeaders;
            public UIntPtr CustomHeadersLen;
        }

        /// <summary>
        /// Header lines 850-933. Self-describing request passed to the
        /// two submit entry points. The host fills the fields relevant
        /// to <see cref="Kind"/>; irrelevant fields must be left
        /// NULL / sentinel (strict validation rejects mismatches with
        /// <c>INVALID_ARGUMENT</c>).
        /// </summary>
        /// <remarks>
        /// All pointers are borrowed for the duration of the submit
        /// call only — the wrapper copies everything it needs before
        /// returning. See <c>CosmosOperationRequestBuilder</c> for safe
        /// construction with managed-string pinning.
        /// </remarks>
        [StructLayout(LayoutKind.Sequential)]
        public struct CosmosOperationRequest
        {
            public CosmosOperationKind Kind;
            public IntPtr Account;
            public IntPtr Database;
            public IntPtr Container;
            public IntPtr ItemId;
            public IntPtr ResourceLink;
            public IntPtr PartitionKey;
            // PR #4515 added an explicit multi-component partition-key path
            // alongside the opaque PartitionKey handle: a pointer to an array
            // of cosmos_partition_key_component_t plus its length. Leave both
            // zero/NULL to keep using the PartitionKey handle field.
            public IntPtr PartitionKeyComponents;
            public UIntPtr PartitionKeyLen;
            public IntPtr FeedRange;
            public CosmosBytesView Body;
            public IntPtr SessionToken;
            public IntPtr ActivityId;
            public IntPtr ContinuationToken;
            public int MaxItemCount;
            public byte PatchMaxAttempts;
            public sbyte PopulateIndexMetrics;
            public sbyte PopulateQueryMetrics;
            public CosmosPreconditionKind PreconditionKind;
            public IntPtr PreconditionEtag;
            public IntPtr Options;

            /// <summary>
            /// Returns a fully-zeroed request with sentinels appropriate
            /// for "all fields unset". Sets <c>MaxItemCount = -1</c>
            /// (the &lt;0 sentinel per header §905) so the driver knows
            /// it is unset rather than literally zero.
            /// </summary>
            public static CosmosOperationRequest Empty => new CosmosOperationRequest
            {
                MaxItemCount = -1,
            };
        }

        // -----------------------------------------------------------------
        // Misc — Phase 0
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_version();

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_string_free(IntPtr s);

        // -----------------------------------------------------------------
        // Response body bytes are read via cosmos_response_body (out ptr/len).
        // The former opaque cosmos_bytes_* handle accessors
        // (cosmos_bytes_data / _len / _free) were removed in PR #4515's
        // redesign — cosmos_bytes_t is now a by-value { ptr, len } struct.
        // -----------------------------------------------------------------

        // -----------------------------------------------------------------
        // Runtime builder — Phase 2 (header lines 1649–1747)
        // NOTE: Only the 5 setters listed below exist. There is no
        // worker_threads / thread_name_prefix / allow_emulator setter —
        // emulator cert handling lives at the driver_options layer (or
        // env-var bundles); Tokio worker count is non-configurable.
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_runtime_builder_new();

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_runtime_builder_free(IntPtr builder);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_runtime_builder_with_workload_id(
            IntPtr builder, byte workloadId);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_runtime_builder_with_correlation_id(
            IntPtr builder, [MarshalAs(UnmanagedType.LPUTF8Str)] string correlationId);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_runtime_builder_with_user_agent_suffix(
            IntPtr builder, [MarshalAs(UnmanagedType.LPUTF8Str)] string suffix);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_runtime_builder_with_wrapping_sdk_identifier(
            IntPtr builder, [MarshalAs(UnmanagedType.LPUTF8Str)] string identifier);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_runtime_builder_with_cpu_refresh_interval_ms(
            IntPtr builder, ulong intervalMs);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_runtime_builder_build(
            IntPtr builder,
            out IntPtr outRuntime,
            out IntPtr outError);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_runtime_free(IntPtr runtime);

        // -----------------------------------------------------------------
        // Completion queue — Phase 1 (header lines 696–767)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_cq_create(IntPtr runtime, in CosmosCqOptions options);

        /// <summary>Pointer-overload — pass <see cref="IntPtr.Zero"/> for defaults.</summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "cosmos_cq_create")]
        public static extern IntPtr cosmos_cq_create_default(IntPtr runtime, IntPtr nullOptions);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_cq_free(IntPtr cq);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_cq_shutdown(IntPtr cq);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosCqState cosmos_cq_state(IntPtr cq);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_cq_wait(IntPtr cq, uint timeoutMs);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint cosmos_cq_wait_batch(
            IntPtr cq,
            [Out] IntPtr[] outCompletions,
            uint maxCount,
            uint timeoutMs);

        // -----------------------------------------------------------------
        // Completion record — Phase 1 (header lines 770–835)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosCompletionOutcome cosmos_completion_outcome(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_user_data(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_op_handle(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_completion_status(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool cosmos_completion_was_cancel_requested(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_take_response(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_response(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_take_error(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_completion_error(IntPtr c);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_completion_free(IntPtr c);

        // -----------------------------------------------------------------
        // Operation handle — Phase 1 (header lines 837–858)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_operation_handle_cancel(IntPtr op);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosOperationHandleState cosmos_operation_handle_state(IntPtr op);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_operation_handle_free(IntPtr op);

        // -----------------------------------------------------------------
        // Account / database / container refs — Phase 3
        // (header lines 617–947, 1640)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_account_ref_with_master_key(
            [MarshalAs(UnmanagedType.LPUTF8Str)] string endpoint,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string key,
            out IntPtr outAccount,
            out IntPtr outError);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_account_ref_clone(
            IntPtr account, out IntPtr outClone);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_account_ref_free(IntPtr account);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_database_ref_create(
            IntPtr account,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string databaseId,
            out IntPtr outDatabase);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_database_ref_free(IntPtr database);

        /// <summary>
        /// Header lines 894–899. Containers are NOT constructed by name —
        /// they are resolved by the driver (potential network round-trip
        /// to read the container's partition-key definition). Sync variant.
        /// </summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_driver_resolve_container_blocking(
            IntPtr runtime,
            IntPtr driver,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string databaseId,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string containerId,
            out IntPtr outContainer,
            out IntPtr outError);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_container_ref_free(IntPtr container);

        // -----------------------------------------------------------------
        // Driver — Phase 3 (header lines 942–997)
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_driver_get_or_create_blocking(
            IntPtr runtime,
            IntPtr account,
            IntPtr options,
            out IntPtr outDriver,
            out IntPtr outError);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_driver_free(IntPtr driver);

        // -----------------------------------------------------------------
        // Partition key — Phase 4 (header lines 1453–1560)
        // The string-only convenience does NOT exist; must use builder.
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_partition_key_builder_new();

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_partition_key_builder_free(IntPtr builder);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_add_string(
            IntPtr builder, [MarshalAs(UnmanagedType.LPUTF8Str)] string value);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_add_number(
            IntPtr builder, double value);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_add_bool(
            IntPtr builder, [MarshalAs(UnmanagedType.U1)] bool value);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_add_null(IntPtr builder);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_add_undefined(IntPtr builder);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_partition_key_builder_build(
            IntPtr builder, out IntPtr outPk);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_partition_key_empty();

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_partition_key_free(IntPtr pk);

        // -----------------------------------------------------------------
        // Feed range (feed_range.rs)
        //
        // The driver's QueryItems contract is feed-range-based, NOT
        // partition-key-based: build_operation's QueryItems arm reads only
        // req.feed_range and never req.partition_key (op_request.rs:685).
        // To scope a query to one logical partition the host must resolve
        // the partition key into a feed range via
        // cosmos_feed_range_for_partition_key (mirrors
        // FeedRange::for_partition(pk, container.partition_key_definition()))
        // and set req.feed_range. A NULL feed_range = whole-container query.
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_feed_range_for_partition_key(
            IntPtr container, IntPtr pk, out IntPtr outFeedRange);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_feed_range_free(IntPtr feedRange);

        // -----------------------------------------------------------------
        // PR #4515 redesign — Phase 6
        //
        // What was REMOVED (do NOT re-add):
        //   - cosmos_operation_{read,create,upsert,replace,delete}_item
        //     factories (operation.rs was deleted; item_factory! macro is gone)
        //   - cosmos_operation_with_body (body now lives on the request struct)
        //   - cosmos_operation_free (no host-owned op handle anymore — the
        //     submit fn takes the request by-borrow + returns an opaque
        //     operation_handle_t; lifetime ownership migrated to the
        //     completion / cancel side)
        //   - cosmos_driver_submit (replaced by the two entry points below)
        //
        // What was ADDED:
        //   - cosmos_operation_options_default     (helper to seed the opts struct)
        //   - cosmos_submit_singleton_operation                 (point ops)
        //   - cosmos_submit_operation                           (feed ops, paginated)
        //   - cosmos_response_next_continuation                 (feed-page token)
        //   - cosmos_response_take_driver / _container          (degenerate-response payloads)
        //
        // The two submit fns are shape-identical; the driver routes on
        // CosmosOperationKind. Both accept the request by const reference;
        // every borrowed pointer inside it (including the body bytes,
        // every UTF-8 string, and the options sub-struct) must remain valid
        // until the call returns. The wrapper deep-copies before returning.
        // -----------------------------------------------------------------

        /// <summary>
        /// Header line 1533. Returns an all-unset
        /// <see cref="CosmosOperationOptions"/>. Equivalent to default
        /// zero-init except the &lt; 0 numeric sentinels are stamped in
        /// explicitly (so future field additions remain forward-compatible).
        /// </summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosOperationOptions cosmos_operation_options_default();

        /// <summary>
        /// Submits a singleton (single-result) operation. Use for point
        /// operations and anything that returns exactly one result — item
        /// CRUD/patch, database/container CRUD, read/replace offer. Feed
        /// kinds MUST go through
        /// <see cref="cosmos_submit_operation"/>.
        /// </summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_submit_singleton_operation(
            IntPtr driver,
            in CosmosOperationRequest request,
            IntPtr queue,
            IntPtr userData,
            out CosmosErrorCode outPreError);

        /// <summary>
        /// Header lines 1894-1898. Submits a feed-capable (paginated)
        /// operation. Resumes from <see cref="CosmosOperationRequest.ContinuationToken"/>
        /// when non-NULL; surfaces the next page's token via
        /// <see cref="cosmos_response_next_continuation"/>. End-of-stream
        /// arrives as a degenerate response: status code 0 + NULL next token.
        /// </summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_submit_operation(
            IntPtr driver,
            in CosmosOperationRequest request,
            IntPtr queue,
            IntPtr userData,
            out CosmosErrorCode outPreError);

        /// <summary>
        /// Header line 1938. Asynchronous variant of
        /// <c>cosmos_driver_get_or_create_blocking</c>; the completion
        /// delivers a degenerate response from which
        /// <see cref="cosmos_response_take_driver"/> moves the new
        /// driver handle out.
        /// </summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_driver_get_or_create_submit(
            IntPtr runtime,
            IntPtr account,
            IntPtr options,
            IntPtr queue,
            IntPtr userData,
            out CosmosErrorCode outPreError);

        /// <summary>
        /// Header line 1954. Asynchronous variant of
        /// <c>cosmos_driver_resolve_container_blocking</c>; the completion
        /// delivers a degenerate response from which
        /// <see cref="cosmos_response_take_container"/> moves the
        /// resolved container handle out.
        /// </summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_driver_resolve_container_submit(
            IntPtr driver,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string databaseId,
            [MarshalAs(UnmanagedType.LPUTF8Str)] string containerId,
            IntPtr queue,
            IntPtr userData,
            out CosmosErrorCode outPreError);

        // -----------------------------------------------------------------
        // Response — Phase 6 (header lines 1562–1729)
        // cosmos_response_body returns int32_t + out-params (NOT a struct).
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern ushort cosmos_response_status_code(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern double cosmos_response_request_charge(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_activity_id(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_session_token(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_etag(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_continuation_token(IntPtr response);

        /// <summary>
        /// Header line 1698. Convenience accessor that exposes the
        /// next-page token for feeds. NULL means end-of-stream (the
        /// driver also stamps status code 0 to be explicit).
        /// </summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_next_continuation(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern CosmosErrorCode cosmos_response_body(
            IntPtr response, out IntPtr outData, out UIntPtr outLen);

        /// <summary>
        /// Header line 1721. Moves the driver handle out of a degenerate
        /// response produced by <see cref="cosmos_driver_get_or_create_submit"/>.
        /// Returns NULL on subsequent calls (one-shot).
        /// </summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_take_driver(IntPtr response);

        /// <summary>
        /// Header line 1729. Moves the container handle out of a degenerate
        /// response produced by <see cref="cosmos_driver_resolve_container_submit"/>.
        /// Returns NULL on subsequent calls (one-shot).
        /// </summary>
        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_response_take_container(IntPtr response);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_response_free(IntPtr response);

        // -----------------------------------------------------------------
        // Rich error — Phase 1 (header lines 1082–1137)
        // NO cosmos_error_kind() — kind lives implicitly in CosmosErrorCode.
        // NO is_throttled/is_not_found/etc. — use cosmos_completion_status
        // and compare against the enum band (2429 = THROTTLED, etc.).
        // -----------------------------------------------------------------

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern ushort cosmos_error_status_code(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern int cosmos_error_sub_status(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool cosmos_error_is_from_wire(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_error_message(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_error_activity_id(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_error_session_token(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_error_etag(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern long cosmos_error_retry_after_ms(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr cosmos_error_backtrace(IntPtr e);

        [DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void cosmos_error_free(IntPtr e);

        // -----------------------------------------------------------------
        // Common helper — borrowed C string → managed String
        // -----------------------------------------------------------------

        /// <summary>Marshal a borrowed UTF-8 C string; returns null for NULL.</summary>
        public static string? PtrToUtf8(IntPtr ptr) =>
            ptr == IntPtr.Zero ? null : Marshal.PtrToStringUTF8(ptr);
    }
}
