# A pipeline with no CI trigger
trigger: none

pr: none

schedules:
- cron: "0 0 * * *" # cron syntax https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers
  displayName: Cosmos Nightly 
  branches:
    include: 
    - master
  always: true # whether to always run the pipeline or only if there have been source code changes since the last run. The default is false


variables:
  ReleaseArguments: ' --filter "TestCategory!=Quarantine" --verbosity normal ' 
  VmImage: windows-latest # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops 
  BuildConfiguration: Release 
  IsNightly: true 


stages:
- stage:
  displayName: Gate 
  jobs:
    - template:  templates/static-tools.yml
      parameters:
        BuildConfiguration: $(BuildConfiguration)
        VmImage: $(VmImage)

    
    - template:  templates/build-test.yml
      parameters:
        BuildConfiguration: $(BuildConfiguration)
        Arguments: $(ReleaseArguments) /p:IsNightly=true /p:GeneratePackageOnBuild=true 
        VmImage: $(VmImage)
          

- stage:
  displayName: Publish 
  jobs:
    - job:
      pool:
        vmImage: $(VmImage)
    
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build Microsoft.Azure.Cosmos
        inputs: 
          command: build  
          configuration: $(BuildConfiguration)
          nugetConfigPath: NuGet.config
          projects: Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj 
          arguments: --configuration $(BuildConfiguration) 
          versioningScheme: OFF
          
      - task: DotNetCoreCLI@2
        displayName: Pack Microsoft.Azure.Cosmos
        inputs: 
          command: pack 
          configuration: $(BuildConfiguration)
          searchPatternPack: Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
          arguments: --configuration $(BuildConfiguration) 
          versioningScheme: OFF
          
      - task: DotNetCoreCLI@2
        displayName: Push Microsoft.Azure.Cosmos
        inputs: 
          command: push 
          configuration: $(BuildConfiguration)
          searchPatternPack: Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
          arguments: --configuration $(BuildConfiguration) 
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '4000bd49-81c3-47f2-94d8-d1392b95c228/04efb628-f46d-4b48-ac4d-5af5b1c75043' #azure-cosmos-dotnet
          versioningScheme: OFF
