# A pipeline with no CI trigger
trigger: none

pr: none

schedules:
- cron: "0 0 * * *" # cron syntax https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers
  displayName: Cosmos Nightly 
  branches:
    include: 
    - master
  always: true # whether to always run the pipeline or only if there have been source code changes since the last run. The default is false


variables:
  VmImage: windows-latest # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops 
  BuildConfiguration: Release
  Packaging.EnableSBOMSigning: true
  Codeql.Enabled: true

stages:
- stage:
  displayName: Generate nightly GA 
  variables:
    Codeql.BuildIdentifier: ga
  jobs:
    - template:  templates/nuget-pack.yml
      parameters:
        BuildConfiguration: Release
        Arguments: /p:IsNightly=true
        VmImage: $(VmImage)
        ReleasePackage: true
        OutputPath: '$(Build.ArtifactStagingDirectory)/bin/AnyCPU/$(BuildConfiguration)/Microsoft.Azure.Cosmos'
        BlobVersion: 'nightly'
        CleanupFolder: true
- stage:
  displayName: Generate nightly preview 
  variables:
    Codeql.BuildIdentifier: preview
  jobs:
    - template:  templates/nuget-pack.yml
      parameters:
        BuildConfiguration: Release
        Arguments: /p:IsNightly=true /p:IsPreview=true
        VmImage: $(VmImage)
        ReleasePackage: true
        OutputPath: '$(Build.ArtifactStagingDirectory)/bin/AnyCPU/$(BuildConfiguration)/Microsoft.Azure.Cosmos'
        BlobVersion: 'nightly-preview'
        CleanupFolder: true
