# A pipeline with no CI trigger
trigger: none

pr: none

variables:
  BuildConfiguration: Release
  Packaging.EnableSBOMSigning: true
  DebugArguments: ' --filter "TestCategory!=Flaky & TestCategory!=Quarantine & TestCategory!=Functional" --verbosity normal '
  ReleaseArguments: ' --filter "TestCategory!=Quarantine" --verbosity normal '
  VmImage: windows-latest # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

stages:
- stage:
  displayName: Pre-publish
  jobs:
    - template: templates/static-tools.yml
      parameters:
        BuildConfiguration: Release
        VmImage:  $(VmImage)
- stage:
  displayName: NugetPack 
  jobs:
    - template: templates/nuget-pack.yml
      parameters:
        BuildConfiguration: Release
        VmImage: $(VmImage)
        ReleasePackage: true
        OutputPath: '$(Build.ArtifactStagingDirectory)/bin/AnyCPU/Release/Microsoft.Azure.Cosmos'
        BlobVersion: 'aot/$(BlobVersion)'

