// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using Xunit;

namespace HdrHistogram.UnitTests
{
    
    internal sealed class LongHistogramEncodingTests : HistogramEncodingTestBase
    {
        internal override HistogramBase Create(long highestTrackableValue, int numberOfSignificantDigits)
        {
            //return new LongHistogram(highestTrackableValue, numberOfSignificantDigits);
            return HistogramFactory.With64BitBucketSize()
                .WithValuesUpTo(highestTrackableValue)
                .WithPrecisionOf(numberOfSignificantDigits)
                .Create();
        }
    }
}
