// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using System.Collections.Generic;
using System.Linq;
using Xunit;

namespace HdrHistogram.UnitTests.Persistence
{
    public sealed class IntConcurrentHistogramLogReaderWriterTests : HistogramLogReaderWriterTestBase
    {
        internal override HistogramBase Create(long highestTrackableValue, int numberOfSignificantValueDigits)
        {
            return new IntConcurrentHistogram(1, highestTrackableValue, numberOfSignificantValueDigits);
        }

        [Theory]
        [MemberData(nameof(PowersOfTwo))]
        public void CanRoundTripSingleHistogramsWithFullRangesOfCountsAndValues(long count)
        {
            RoundTripSingleHistogramsWithFullRangesOfCountsAndValues(count);
        }

        public static IEnumerable<object[]> PowersOfTwo()
        {
            return TestCaseGenerator.PowersOfTwo(31)
                .Select(v=>new object[1]{v});
        }
    }
}