//------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//------------------------------------------------------------

// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using System;

namespace Microsoft.Data.Encryption
{
    /// <summary>
    /// Represents an exception thrown by the Data Encryption SDK.
    /// </summary>
    internal sealed class MicrosoftDataEncryptionException : Exception
    {
        /// <summary>
        /// Initializes a new instance of MicrosoftDataEncryptionException with the specified error message.
        /// </summary>
        /// <param name="message">The message describing the error.</param>
        public MicrosoftDataEncryptionException(string message) : base(message) { }
    }
}
