// ------------------------------------------------------------
// The code in this repository code was written by Lee Campbell, as a
// derived work from the original Java by Gil Tene of Azul Systems and
// Michael Barker, and released to the public domain, as explained
// at http://creativecommons.org/publicdomain/zero/1.0/
// ------------------------------------------------------------

// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

namespace HdrHistogram.Encoding
{
    internal sealed class RecordedData : IRecordedData
    {
        public RecordedData(int cookie, int normalizingIndexOffset, int numberOfSignificantValueDigits, long lowestDiscernibleValue, long highestTrackableValue, double integerToDoubleValueConversionRatio, long[] counts)
        {
            Cookie = cookie;
            NormalizingIndexOffset = normalizingIndexOffset;
            NumberOfSignificantValueDigits = numberOfSignificantValueDigits;
            LowestDiscernibleValue = lowestDiscernibleValue;
            HighestTrackableValue = highestTrackableValue;
            IntegerToDoubleValueConversionRatio = integerToDoubleValueConversionRatio;
            Counts = counts;
        }

        public int Cookie { get; }
        public int NormalizingIndexOffset { get; }
        public int NumberOfSignificantValueDigits { get; }
        public long LowestDiscernibleValue { get; }
        public long HighestTrackableValue { get; }
        public double IntegerToDoubleValueConversionRatio { get; }
        public long[] Counts { get; }
    }
}