// ------------------------------------------------------------
// The code in this repository code was written by Lee Campbell, as a
// derived work from the original Java by Gil Tene of Azul Systems and
// Michael Barker, and released to the public domain, as explained
// at http://creativecommons.org/publicdomain/zero/1.0/
// ------------------------------------------------------------

// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using System.Collections.Generic;

namespace HdrHistogram
{
    /// <summary>
    /// Defines a method for reading Histogram logs in the v1 format.
    /// </summary>
    internal interface IHistogramLogV1Reader
    {
        /// <summary>
        /// Reads a v1 formatted histogram log.
        /// </summary>
        /// <returns>Returns a sequence of <see cref="HistogramBase"/> items.</returns>
        IEnumerable<HistogramBase> ReadHistograms();
    }
}