//------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//------------------------------------------------------------

// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

namespace Microsoft.Data.Encryption.Cryptography
{
    /// <summary>
    /// Represents the encryption algorithms supported for data encryption.
    /// </summary>
    internal enum DataEncryptionKeyAlgorithm
    {
        /// <summary>
        /// Represents the authenticated encryption algorithm with associated data as described in 
        /// http://tools.ietf.org/html/draft-mcgrew-aead-aes-cbc-hmac-sha2-05.
        /// </summary>
        AEAD_AES_256_CBC_HMAC_SHA256
    }
}
