// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

namespace Microsoft.Data.Encryption.Cryptography
{
    /// <summary>
    /// Represents the encryption algorithms supported for key encryption.
    /// </summary>
    internal enum KeyEncryptionKeyAlgorithm
    {
        /// <summary>
        /// RSA public key cryptography algorithm with Optimal Asymmetric Encryption Padding (OAEP) padding.
        /// </summary>
        RSA_OAEP
    }
}