$a = Get-Content $args[0]
$b = "// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis."
$c = "// <auto-generated/>"
$d = ""
Set-Content $args[0] -value $b, $c, $d, $a