# File: templates/build-fault-injection-test.yml

parameters:
  BuildConfiguration: ''
  Arguments: ''
  VmImage: '' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  OS: 'Windows'
  MultiRegionConnectionString : ''
  IncludeEncryption: true
  IncludePerformance: true
  IncludeCoverage: true

jobs:

- job:
  displayName: FaultInjection Tests ${{ parameters.BuildConfiguration }} - ${{ parameters.EmulatorPipeline4CategoryListName }}
  timeoutInMinutes: 60
  condition: and(succeeded(), eq('${{ parameters.OS }}', 'Windows'))
  pool:
    name: 'OneES'

  steps:
  - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
    clean: true  # if true, execute `execute git clean -ffdx && git reset --hard HEAD` before fetching

  # Add this Command to Include the .NET 6 SDK
  - task: UseDotNet@2
    displayName: Use .NET 6.0
    inputs:
      packageType: 'runtime'
      version: '6.x'      

  - task: UseDotNet@2
    displayName: Use .NET 8.0
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - task: DotNetCoreCLI@2
    displayName: Fault Injection Tests
    retryCountOnTaskFailure: 2
    condition: succeeded()
    inputs:
      command: test
      projects: 'Microsoft.Azure.Cosmos/FaultInjection/tests/*.csproj'
      arguments: $ --configuration ${{ parameters.BuildConfiguration }} /p:OS=${{ parameters.OS }}
      nugetConfigPath: NuGet.config
      publishTestResults: true
      testRunTitle: FaultInjectionTests
    env: 
      COSMOSDB_MULTI_REGION: ${{ parameters.MultiRegionConnectionString }}
      AZURE_COSMOS_NON_STREAMING_ORDER_BY_FLAG_DISABLED: true