# File: templates/nuget-pack.yml

parameters:
  BuildConfiguration: ''
  Arguments: ''
  VmImage: '' # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  OS: 'Windows'
  OutputPath: ''
  GenerateSymbols: true

jobs:
- job: GenerateNugetPackages
  displayName: Generate Nuget packages
  pool:
    vmImage: ${{ parameters.VmImage }}

  steps:
  - task: DotNetCoreCLI@2
    displayName: Build Microsoft.Azure.Cosmos
    inputs: 
      command: build  
      configuration: $(BuildConfiguration)
      nugetConfigPath: NuGet.config
      projects: Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj 
      arguments: --configuration ${{ parameters.BuildConfiguration }} -p:Optimize=true 
      versioningScheme: OFF

  - task: DotNetCoreCLI@2
    displayName: 'Create SDK NuGet Package'
    inputs:
      command: custom
      projects: 'Microsoft.Azure.Cosmos\src\Microsoft.Azure.Cosmos.csproj'
      custom: pack
      arguments: '-v detailed -c ${{ parameters.BuildConfiguration }} --no-build --no-restore -o "${{ parameters.OutputPath }}"'

  - ${{ if eq(parameters.GenerateSymbols, true) }}:
    - task: DotNetCoreCLI@2
      displayName: 'Create SDK NuGet Symbols Package'
      inputs: 
        command: custom
        projects: 'Microsoft.Azure.Cosmos\src\Microsoft.Azure.Cosmos.csproj'
        custom: pack
        arguments: '-v detailed -c ${{ parameters.BuildConfiguration }} --no-build --include-symbols /p:SymbolPackageFormat=snupkg --no-restore -o "${{ parameters.OutputPath }}"'
